language: python
sudo: false
python:
  - 2.7
before_install:
  - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels ~/travis-wheels
install:
  - PIP_FIND_LINKS=~/travis-wheels/wheelhouse pip install -r dev-requirements.txt -e .
script:
  - py.test -v -x
